[build]
  base = "webs"
  command = "yarn build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"
  GATSBY_CONTINUE_BUILD_ON_MISSING_ADAPTER = "true"
  GATSBY_SANITY_DATASET = "production"
  NPM_FLAGS = "--version"
  YARN_FLAGS = "--version"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
