headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\raney\\Programming\\hof-gatsby-sanity\\webs\\public"
publishOrigin = "config"
base = "C:\\Users\\raney\\Programming\\hof-gatsby-sanity\\webs"
command = "node build.js"
commandOrigin = "config"

[build.environment]
NODE_VERSION = "20"
GATSBY_CONTINUE_BUILD_ON_MISSING_ADAPTER = "true"
GATSBY_SANITY_DATASET = "production"
NPM_FLAGS = "--version"
YARN_FLAGS = "--version"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
cache-control = "public, max-age=0, must-revalidate"
x-xss-protection = "1; mode=block"
x-content-type-options = "nosniff"
referrer-policy = "same-origin"
x-frame-options = "DENY"

[[headers]]
for = "/static/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/styles.bdd6090ba3484231b79b.css/"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-0b28d87d527d752a5691.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-0b28d87d527d752a5691.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-060c9bf4e2a8cddfb9f5.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-060c9bf4e2a8cddfb9f5.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-060c9bf4e2a8cddfb9f5.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/396-cb7d53bb63033126bbf9.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/396-cb7d53bb63033126bbf9.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/396-cb7d53bb63033126bbf9.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-0813d677a51627db76f1.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-0813d677a51627db76f1.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-0813d677a51627db76f1.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-nominate-index-js-2ff3b3a1a7155f7ba420.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-nominate-index-js-2ff3b3a1a7155f7ba420.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-founders-series-index-js-3d75817e73ac44bceee3.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-founders-series-index-js-3d75817e73ac44bceee3.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-book-index-js-e1fafc534fa81bab4484.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-book-index-js-e1fafc534fa81bab4484.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-media-index-js-f8a88fbeea6ed0167617.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-media-index-js-f8a88fbeea6ed0167617.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-templates-inductees-inductee-bio-js-867a78871367f70821f2.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-templates-inductees-inductee-bio-js-867a78871367f70821f2.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-fellowship-index-js-f8bcde7f3fa86d03e9c5.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-fellowship-index-js-f8bcde7f3fa86d03e9c5.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-induction-dinner-index-js-bb817278eaa9c9451568.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-induction-dinner-index-js-bb817278eaa9c9451568.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-a9079d3333e9fb3222c9.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-a9079d3333e9fb3222c9.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-investors-mentors-index-js-63e538d9ab4dcac79733.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-investors-mentors-index-js-63e538d9ab4dcac79733.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/672-9c0700c93772f00cbf55.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/672-9c0700c93772f00cbf55.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-6956dcdb0fc9ff19b01e.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-6956dcdb0fc9ff19b01e.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]