headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\raney\\Programming\\hof-gatsby-sanity\\webs\\public"
publishOrigin = "config"
base = "C:\\Users\\raney\\Programming\\hof-gatsby-sanity\\webs"
command = "node build.js"
commandOrigin = "config"

[build.environment]
NODE_VERSION = "20"
GATSBY_SANITY_DATASET = "production"
NPM_FLAGS = "--version"
YARN_FLAGS = "--version"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
cache-control = "public, max-age=0, must-revalidate"
x-xss-protection = "1; mode=block"
x-content-type-options = "nosniff"
referrer-policy = "same-origin"
x-frame-options = "DENY"

[[headers]]
for = "/static/*"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/styles.e17fcc235f8c5ca68fb4.css/"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-6775f4d663ce03d18603.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-index-js-6775f4d663ce03d18603.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/framework-3576abd7332dde9e72aa.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-1aa0c9f3fe0a88b3686b.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-1aa0c9f3fe0a88b3686b.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/commons-1aa0c9f3fe0a88b3686b.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/312-43aaf9112eb5e37e5451.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/312-43aaf9112eb5e37e5451.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/312-43aaf9112eb5e37e5451.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-03e7afde88e8aefadd55.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-03e7afde88e8aefadd55.js.LICENSE.txt"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/app-03e7afde88e8aefadd55.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-nominate-index-js-80631390c3e8de5fbbc0.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-nominate-index-js-80631390c3e8de5fbbc0.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-founders-series-index-js-555578de2899f0b80a84.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-founders-series-index-js-555578de2899f0b80a84.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-book-index-js-33d88859e6729b9617f7.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-book-index-js-33d88859e6729b9617f7.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-media-index-js-6a6c41353d5124beaf38.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-media-index-js-6a6c41353d5124beaf38.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-templates-inductees-inductee-bio-js-760d94f5c28062a8bdbd.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-templates-inductees-inductee-bio-js-760d94f5c28062a8bdbd.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-fellowship-index-js-a5f263b53f596768a73b.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-fellowship-index-js-a5f263b53f596768a73b.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-induction-dinner-index-js-06b620e6311656f2ef70.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-induction-dinner-index-js-06b620e6311656f2ef70.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-investors-mentors-index-js-87c7940177ba9fa4d95c.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-investors-mentors-index-js-87c7940177ba9fa4d95c.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-35458eac85822b706d22.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/webpack-runtime-35458eac85822b706d22.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/672-9c0700c93772f00cbf55.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/672-9c0700c93772f00cbf55.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-14529a7d9f81d4515205.js"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/component---src-pages-404-js-14529a7d9f81d4515205.js.map"

[headers.values]
cache-control = "public, max-age=31536000, immutable"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]